/* Inspiring quotes for the good-morning greeting (ESM).
 * The scheduler tracks which have been sent (users/{uid}.usedQuotes) and never
 * repeats one until the whole list has been shown, then reshuffles.
 * Add more freely — order doesn't matter.
 */
export const QUOTES = [
  "The secret of getting ahead is getting started. — Mark Twain",
  "Well begun is half done. — Aristotle",
  "Little by little, one travels far. — J.R.R. Tolkien",
  "What you do today can improve all your tomorrows. — Ralph Marston",
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
  "The best way to predict the future is to create it. — Peter Drucker",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "It always seems impossible until it's done. — Nelson Mandela",
  "A year from now you may wish you had started today. — Karen Lamb",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "The journey of a thousand miles begins with a single step. — Lao Tzu",
  "You are never too old to set another goal or dream a new dream. — C.S. Lewis",
  "Quality is not an act, it is a habit. — Aristotle",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "Dream big and dare to fail. — Norman Vaughan",
  "Act as if what you do makes a difference. It does. — William James",
  "Success is the sum of small efforts repeated day in and day out. — R. Collier",
  "The future depends on what you do today. — Mahatma Gandhi",
  "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
  "Great things are done by a series of small things brought together. — Van Gogh",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Sometimes later becomes never. Do it now.",
  "Wake up with determination, go to bed with satisfaction.",
  "Little things make big days.",
  "It's going to be hard, but hard does not mean impossible.",
  "Don't wait for opportunity. Create it.",
  "The key to success is to start before you are ready. — Marie Forleo",
  "Progress, not perfection.",
  "A smooth sea never made a skilled sailor. — F.D. Roosevelt",
  "Fall seven times, stand up eight. — Japanese proverb",
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
  "Doubt kills more dreams than failure ever will. — Suzy Kassem",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Happiness is not something ready made. It comes from your own actions. — Dalai Lama",
  "Every morning is a new page in your story.",
  "Bloom where you are planted.",
  "Small steps every day add up to big results.",
  "Today is a good day to have a good day.",
  "Be the energy you want to attract.",
  "Courage doesn't always roar; sometimes it's a quiet 'I'll try again tomorrow.'",
  "The comeback is always stronger than the setback.",
  "You are capable of amazing things.",
  "Focus on the step in front of you, not the whole staircase.",
  "Gratitude turns what we have into enough.",
  "A little progress each day adds up to big results.",
  "Discipline is choosing between what you want now and what you want most.",
  "Slow progress is still progress.",
  "Make each day your masterpiece. — John Wooden",
  "The best time to plant a tree was 20 years ago. The second best is now.",
  "Difficult roads often lead to beautiful destinations.",
  "Stars can't shine without darkness.",
  "You didn't come this far to only come this far.",
  "One day or day one. You decide.",
  "Be so good they can't ignore you. — Steve Martin",
  "Trust the timing of your life.",
  "Grow through what you go through.",
  "Your only limit is you.",
  "Keep going. Everything you need will come to you at the perfect time.",
];
